<h1>Les 01. Beeldherkenning</h1>

NB als je np.matrix gebruikt ipv np.array koen er hele andere getallen uit. Waarom? Is het bij np.matrx misschien een dot product ipv een gewone vermenigvuldiging?

NB2 eigenlijk is er ook nog een bias in de functie nodig:
https://stackoverflow.com/questions/2448015/2d-convolution-using-python-and-numpy

In [3]:
import numpy as np

In [42]:
image = np.array([[8,4,2,3,9,1],[0,6,4,3,7,10],[2,0,1,3,5,8],[6,3,1,4,8,2],[0,2,4,3,5,9],[2,7,9,1,3,5]])
print(image)
print()
print(image.shape)

[[ 8  4  2  3  9  1]
 [ 0  6  4  3  7 10]
 [ 2  0  1  3  5  8]
 [ 6  3  1  4  8  2]
 [ 0  2  4  3  5  9]
 [ 2  7  9  1  3  5]]

(6, 6)


In [43]:
kernel = np.array([[2,0,3],[1,1,0],[3,-1,4]])
print(kernel)
print()
print(kernel.shape)

[[ 2  0  3]
 [ 1  1  0]
 [ 3 -1  4]]

(3, 3)


In [48]:
def convolution(image, kernel):
    m, n = kernel.shape
    print('m = ',m)
    print('n = ',n)
    if (m == n):
        y, x = image.shape
        y = y - m + 1
        x = x - n + 1
        print('y = ',y)
        print('x = ',x)
        new_image = np.zeros((y,x))
        print(new_image)
        for i in range(y):
            for j in range(x):
                new_image[i][j] = np.sum(image[i:i+m, j:j+n]*kernel)
    return new_image

In [49]:
new_image = convolution(image, kernel)

m =  3
n =  3
y =  4
x =  4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [50]:
print(new_image)

[[38. 38. 58. 55.]
 [33. 46. 64. 56.]
 [30. 27. 51. 82.]
 [52. 40. 71. 42.]]


Opdracht B

In [58]:
def zero_pad(X,pad):
    return np.pad(X, ((pad,pad),(pad,pad)), 'constant')

In [59]:
print(zero_pad(image,2))

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  4  2  3  9  1  0  0]
 [ 0  0  0  6  4  3  7 10  0  0]
 [ 0  0  2  0  1  3  5  8  0  0]
 [ 0  0  6  3  1  4  8  2  0  0]
 [ 0  0  0  2  4  3  5  9  0  0]
 [ 0  0  2  7  9  1  3  5  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
